{{- if .Values.networking.usedForAccess }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mesh.fullname" . }}
  labels:
    {{- include "mesh.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.networking.gateway.name }}
    namespace: {{ .Values.networking.gateway.namespace }}
  {{- with .Values.networking.gateway.hostname }}
  hostnames:
    - {{ . | quote }}
  {{- end }}
  {{- with .Values.networking.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
