{{- if .Values.usedForAccess }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mesh.fullname" . }}
  labels:
    {{- include "mesh.labels" . | nindent 4 }}
spec:
  parentRefs:
  - name: {{ .Values.gateway.name }}
    namespace: {{ .Values.gateway.namespace }}
  {{- with .Values.gateway.hostname }}
  hostnames:
    - {{ . | quote }}
  {{- end }}
  {{- with .Values.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
