---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-options
  labels:
    {{- include "istio-ingress.labels" . | nindent 4 }}
data:
  {{- if .Values.hpa.enabled }}
  horizontalPodAutoscaler: |
    spec:
      minReplicas: {{ .Values.hpa.minReplicas }}
      maxReplicas: {{ .Values.hpa.maxReplicas }}
  {{- end }}
  {{- with .Values.deployment.labels }}
  deployment: |
    metadata:
      labels:
        {{- toYaml . | nindent 8 }}
  {{- end }}
