---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "istio-ingress.gateway-name" . }}
  labels:
    {{- include "istio-ingress.labels" . | nindent 4 }}
spec:
  gatewayClassName: istio
  infrastructure:
    parametersRef:
      group: ""
      kind: ConfigMap
      name: {{ include "istio-ingress.gateway-name" . }}-options
  listeners:
    - name: http
      port: {{ .Values.port }}
      protocol: HTTP
      hostname: {{ .Values.hostnameGlob | quote }}
      allowedRoutes:
        namespaces:
          from: Selector
          selector:
            matchLabels:
              istio.io/{{ include "istio-ingress.gateway-name" . }}-access: "true"
