---
apps:
  httpbingoA:
    serviceName: httpbingo-a
    servicePort: 8000
  httpbingoB:
    serviceName: httpbingo-b
    servicePort: 8000
  httpbingoC:
    serviceName: httpbingo-c
    servicePort: 8000

gateway:
  name: main-gateway
  namespace: istio-ingress
  hostname: "httpbin.there-is-no-point.localhost"
