{{- if .Values.addAWaypoint }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mesh.fullname" . }}
  labels:
    {{- include "mesh.labels" . | nindent 4 }}
spec:
  parentRefs:
  - group: ""
    kind: Service
    name: {{ include "mesh.fullname" . }}
    port: {{ .Values.waypointService.port }}
  {{- with .Values.rules }}
  rules:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
