{{- if .Values.networking.addAWaypoint }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "mesh.fullname" . }}
  labels:
    {{- include "mesh.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      targetPort: {{ .Values.networking.waypointService.port }}
      port: {{ .Values.networking.waypointService.port }}
{{- end }}
