# Ref: https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/
---
commonLabels:
  domain: mesh
  phase: config

releases:
  - name: istio-config
    namespace: istio-system
    createNamespace: true
    chart: ../charts/cluster/istio-config

  - name: istio-ingress-main-gateway
    namespace: istio-ingress
    createNamespace: true
    chart: ../charts/cluster/istio-ingress
    values:
      - ./values/mesh-global-config/istio-ingress/main-gateway.yaml

  - name: istio-ingress-jwt-authentication-gateway
    namespace: istio-ingress
    createNamespace: true
    chart: ../charts/cluster/istio-ingress
    values:
      - ./values/mesh-global-config/istio-ingress/jwt-authentication-gateway.yaml
