---
hostnameGlob: "*.there-is-no-point.localhost"
hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
deployment:
  labels:
    gateway-options-deployment: set-by-istio-ingress
jwtRules:
  - issuer: "testing@secure.istio.io"
    jwksUri: "https://raw.githubusercontent.com/istio/istio/release-1.27/security/tools/jwt/samples/jwks.json"
requireJwtHostname:
  - httpbin.there-is-no-point.localhost
