---
permissiveMtls: false

networking:
  usedForAccess: false
  gateway:
    name: ""
    namespace: ""
    hostname: ""

  addAWaypoint: false
  waypointService:
    targetPort: http
    port: 8000

  rules: []

authorization:
  addAuthorizations: false
  jwtRules: []
  rules: []
