---
networking:
  usedForAccess: false
  gateway:
    name: ""
    namespace: ""
    hostname: ""

  addAWaypoint: false
  waypointService:
    port: ""

  rules: []

authorization:
  addAuthorizations: false
  rules: []
